SELECT EMPLOYEE_ID ,FIRST_NAME,SALARY,COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL;


SELECT DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;


--부서장이 없는 부서만 조회

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;


SELECT *
FROM DEPARTMENTS
WHERE MANAGER_ID IS NULL;


--문제1) 직책이 AD_PRES, IT_PROG, FI_MGR, FI_ACCOUNT 에 해당하는
--직원의 이름과 직책정보,급여 정보를 조회
SELECT FIRST_NAME,JOB_ID,SALARY
FROM EMPLOYEES
WHERE JOB_ID IN ('AD_PRES','IT_PORG','FI_MGR','FI_ACCOUNT');

SELECT * 
FROM EMPLOYEES;


--문제2) EMAIL정보가 DLEE,SANDE,KGEE에 해당하는 직원의 이름과 이메일 핸드폰번호 정보 조회하시오.
SELECT FIRST_NAME,EMAIL,PHONE_NUMBER
FROM   EMPLOYEES
WHERE EMAIL IN ('DLEE','SANDE','KGEE');


--문제3) MANAGER_ID가 100,101,102,103,104 에 해당하지 않는 직원의 이름과 매니저ID, 급여 정보를 조회하시오.
SELECT FIRST_NAME,MANAGER_ID,SALARY
FROM EMPLOYEES
WHERE MANAGER_ID NOT IN (100,101,102,103,104)
ORDER BY MANAGER_ID ASC;


--BEETWEEN 연산자
--일정 범위 내의 데이터를 조회할때 사용하는 연산자

--급여가 10000이상 20000이하의 범위의 받고있는 직원의 이름과 급여 정보 조회해주세요.

SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY >=10000
AND SALARY <=20000
ORDER BY SALARY ASC;



--BEETWEEN연산자 활용
-- BEETWEEN A AND B
-- A (최솟값) 이상(>=)  B(최댓값) 이하(<=)

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 10000 AND 20000;



SELECT FIRST_NAME
FROM EMPLOYEES 
WHERE FIRST_NAME LIKE 'S%n';



SELECT PHONE_NUMBER  FROM EMPLOYEES;
DESC EMPLOYEES;

--문제1) PHONE_NUMBER가 650으로 시작하는 직원의 정보(PHONE_NUMBER) 가져오기
SELECT PHONE_NUMBER
FROM    EMPLOYEES
WHERE   PHONE_NUMBER LIKE '650%';
--문제2) FIRST_NAME이 it으로 끝나고 총4글자인 직원 정보(FIRST_NAME)가져오기
SELECT FIRST_NAME
FROM    EMPLOYEES
WHERE  FIRST_NAME  LIKE '__it';

--문제3) FIRST_NAME의 두번째 글자가 e인 직원의 FIRST_NAME 가져오기

SELECT FIRST_NAME
FROM    EMPLOYEES
WHERE  FIRST_NAME  LIKE '_e%';
